### ISSUE TITLE
Migrate to Gradle and Android Studio

### ISSUE THREAD

**Issue by johnjohndoe** [georgjaehnig/serchilo-android#15]
It would be handy if you can migrate your project to use the Gradle build system and Android Studio as the IDE of choice. The import wizard of the IDE will automatically convert the directory structure of the Eclipse project for you.

**Comment by georgjaehnig** [comment]
By now, I'm a bit reluctant to continue development on this native app and would prefer much more to switch to a mobile framework, where I can have one code base and compile it to Android, iOS and so on.

I wrote here about it, maybe you also have a suggestion:
https://groups.google.com/forum/#!topic/serchilo/nwOLjiVm0Z0
(and feel free to subsribe to the Google group)!

**Comment by johnjohndoe** [comment]
Thank you for the clarification. I am only interested in Android as of now. You might want to update the README to reflect the "pending" status of the project.
